/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package margo.view;

import controller.ClasseController;
import controller.EtudiantController;
import javax.swing.JComboBox;

/**
 *
 * @author Mtomas
 */
public class UserPanel extends javax.swing.JPanel {

  /**
   * Creates new form UserPanel
   */
  public UserPanel() {
    initComponents();    
    
  }
  
  public UserPanel(String user) {
    initComponents();    
    switch(user) {
      case "student":
        HomeTab.remove(studentsScroll);
        HomeTab.remove(classes);
        
        break;
      case "teacher":
        HomeTab.remove(classes);
          break;
      case "admin":
        //HomeTab.remove(Accueil);
          break;
      default:
        
    }
    ClasseController tmpClasse=new ClasseController() ;
    classesTable.setModel(tmpClasse.Update());
    
    ClasseController tmpClasseEtudiant=new ClasseController() ;    
    ListClasseB.setModel(tmpClasseEtudiant.GetListClasse());  
    
    
    
    EtudiantController tmpEtudiant=new EtudiantController() ;
    studentsTable.setModel(tmpEtudiant.Update(ListClasseB.getSelectedItem().toString()));
    
  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeTab = new javax.swing.JTabbedPane();
        Accueil = new javax.swing.JScrollPane();
        AccueilTextArea1 = new javax.swing.JTextArea();
        classes = new javax.swing.JScrollPane();
        classesTable = new javax.swing.JTable();
        students = new javax.swing.JPanel();
        studentsScroll = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        ListClasseB = new javax.swing.JComboBox();
        account = new javax.swing.JPanel();
        jLabelUsername = new javax.swing.JLabel();
        AccountUserName = new javax.swing.JTextField();
        jLabelUserPassword = new javax.swing.JLabel();
        AccountPassword = new javax.swing.JPasswordField();
        jLabelEmail = new javax.swing.JLabel();
        AccountEmail = new javax.swing.JTextField();

        HomeTab.setName(""); // NOI18N
        HomeTab.setOpaque(true);
        HomeTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HomeTabFocusGained(evt);
            }
        });

        AccueilTextArea1.setColumns(20);
        AccueilTextArea1.setRows(5);
        AccueilTextArea1.setText("Hello!\n\nWelcome to MARGO application.\n\nUse the top tabs to navigate within the app.");
        Accueil.setViewportView(AccueilTextArea1);

        HomeTab.addTab("Home", Accueil);

        classesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "(Code Classe)", "(Lib Classe)", "(Code Filiere)"
            }
        ));
        classes.setViewportView(classesTable);

        HomeTab.addTab("Classes", classes);

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "(ID)", "(Nom)", "(Prenom)", "(Situation)", "(Adresse)"
            }
        ));
        studentsScroll.setViewportView(studentsTable);

        ListClasseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListClasseBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentsLayout = new javax.swing.GroupLayout(students);
        students.setLayout(studentsLayout);
        studentsLayout.setHorizontalGroup(
            studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addGroup(studentsLayout.createSequentialGroup()
                        .addComponent(ListClasseB, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        studentsLayout.setVerticalGroup(
            studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ListClasseB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(studentsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        HomeTab.addTab("Students", students);

        jLabelUsername.setText("Username");

        AccountUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountUserNameActionPerformed(evt);
            }
        });

        jLabelUserPassword.setText("Password");

        jLabelEmail.setText("Email address");

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account);
        account.setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabelUsername))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUserPassword)
                            .addComponent(jLabelEmail))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AccountUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(AccountPassword)
                    .addComponent(AccountEmail))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername)
                    .addComponent(AccountUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(AccountEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        HomeTab.addTab("My account", account);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeTab, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        HomeTab.getAccessibleContext().setAccessibleName("Home");
    }// </editor-fold>//GEN-END:initComponents

  private void AccountUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountUserNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_AccountUserNameActionPerformed

    private void HomeTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HomeTabFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeTabFocusGained

    private void ListClasseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListClasseBActionPerformed
        // TODO add your handling code here:
        EtudiantController tmpEtudiant=new EtudiantController() ;
        studentsTable.setModel(tmpEtudiant.Update(ListClasseB.getSelectedItem().toString()));
    }//GEN-LAST:event_ListClasseBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountEmail;
    private javax.swing.JPasswordField AccountPassword;
    private javax.swing.JTextField AccountUserName;
    private javax.swing.JScrollPane Accueil;
    private javax.swing.JTextArea AccueilTextArea1;
    private javax.swing.JTabbedPane HomeTab;
    private javax.swing.JComboBox ListClasseB;
    private javax.swing.JPanel account;
    private javax.swing.JScrollPane classes;
    private javax.swing.JTable classesTable;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelUserPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel students;
    private javax.swing.JScrollPane studentsScroll;
    private javax.swing.JTable studentsTable;
    // End of variables declaration//GEN-END:variables
}
